//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveUrselfProducts
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int id { get; set; }
        public string Наименование_товара { get; set; }
        public string C_Главное_изображение { get; set; }
        public string C_Производитель { get; set; }
        public string C_Активен_ { get; set; }
        public string C_Цена { get; set; }
    }
}
